[server]
host ="127.0.0.1"
port = 8088

[mysql]
hostname = "localhost"
config = "charset=utf8mb4&parseTime=True&loc=Local"
port = 13316
username = "root"
password = "root"
database = "goeasydb"

[redis]
host = "127.0.0.1"
port = 6379
username = ""
password = ""

[zap]
level = "info"
prefix = "[golang] "
format = "console"
director = "logs"
encode-level = "LowercaseColorLevelEncoder"
stacktrace-key = "stacktrace"
show-line = true
log-in-console = true