// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Guohuixixi/go-easy/core"
	"github.com/Guohuixixi/go-easy/core/bootstrap"
	"github.com/Guohuixixi/go-easy/core/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() (core.Application, error) {
	viper := bootstrap.NewViper()
	config := bootstrap.NewConfig(viper)
	db := bootstrap.NewMysql(config)
	cmdable := bootstrap.NewRedis(config)
	logger := bootstrap.NewZap(config)
	engine := bootstrap.NewServer()
	application := core.NewApplication(config, viper, db, cmdable, logger, engine)
	return application, nil
}

// wire.go:

var BaseProvider = wire.NewSet(bootstrap.NewViper, bootstrap.NewConfig, bootstrap.NewMysql, bootstrap.NewRedis, bootstrap.NewZap, logger.NewZapLogger, core.NewApplication)

var WebProvider = wire.NewSet(bootstrap.NewServer)
